-- SQL insert statements for 50 dental equipment items
BEGIN;
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMWGAGKJA90S2QEZQ9', 'Dental Chair', 'A-dec 511', 'A-dec', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM6QYKHR0SZEMZE4FM', 'Dental Delivery System', 'A-dec 500', 'A-dec', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM9Y67S15P6WEWC4JV', 'Operatory Light', 'A-dec LED Operatory Light', 'A-dec', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM0EE335BE404G21G8', 'High-Speed Handpiece', 'KaVo EXPERTtorque E680', 'KaVo', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMPKS08SAS820MXXEC', 'High-Speed Handpiece', 'NSK Ti-Max X450', 'NSK', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMKMHBQ078KA295ASH', 'Low-Speed Handpiece', 'Midwest Tribute', 'Midwest', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMA3GYKWDD83TAKCNH', 'Dental Air Compressor', 'Cattani Turbo 60', 'Cattani', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM7ZVDD5ZFYBNARV7C', 'Saliva Ejector', NULL, 'DentalEZ', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM8FEGTWVNVF02PW27', 'High-Volume Evacuator (HVE)', NULL, 'Satelec / Acteon', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMF8C5ZF8GPEADMNRT', 'Ultrasonic Scaler', 'Cavitron Select', 'Dentsply Sirona', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM7XRW63BBAP1VW5D4', 'Autoclave (Steam Sterilizer)', 'Tuttnauer 3870E', 'Tuttnauer', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMCZ6FPK7KY7THM5AW', 'Benchtop Autoclave', 'Midmark M11', 'Midmark', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMHAVG1KF1GZFBA4PD', 'Digital Intraoral X-ray Sensor', 'DEXIS Platinum', 'DEXIS (KaVo)', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMWKCNWJM3F0N8CW1C', 'Intraoral Camera', 'Sopro 717', 'Acteon (Sopix)', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMHNF5C3S0CEH7CFCX', 'Panoramic X-ray (Pan/CEPH)', 'Planmeca ProMax 3D', 'Planmeca', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMK8NNVEKTV86RSS73', 'Cone Beam CT (CBCT)', 'Carestream CS 9300', 'Carestream', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMZ7FNXX803G0RM18C', 'Dental Curing Light', '3M Elipar Deep Cure', '3M', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMHD6WJ1NMQH86EEB8', 'Curing Light (LED)', 'Ivoclar Bluephase Style', 'Ivoclar', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM2JDWFFRMNJVZWX0J', 'Dental Sterilization Center (Instrument Washer)', 'Midmark M11 Ultraclave', 'Midmark', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMWJAHWMH6YEH52BVE', 'Ultrasonic Cleaner', 'Elmasonic S 100', 'Elma', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMMB61WJ4G5P717ADN', 'Dental Lab Model Trimmer', NULL, 'Whip Mix', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMYX5ZBPZN9XZQKQXV', 'Articulator', 'Artex CR', 'Kavo', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM5N6DGF9PPE0ZYM2D', 'Vacuum Forming Machine', 'Biostar 3000', 'Scheu-Dental', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMMKW6S41X4YE6JGGX', 'Dental Surgical Microscope', 'Zeiss OPMI pico', 'Zeiss', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMW7Z9A93DHQB77SCW', 'Endodontic Motor', 'Dentsply X-SMART Plus', 'Dentsply Sirona', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMYKPPZCXC1E6PABDM', 'Apex Locator', 'Root ZX II', 'J. Morita', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMSRWBAQK0N9ZJH2K9', 'Intraoral Scanner', 'iTero Element 5D', 'Align Technology (iTero)', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM2VJHVP1NYKCW3T2H', 'Dental Laser', 'Waterlase iPlus', 'BIOLASE', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM2FY6AZRWB19VSF9W', 'Amalgam Separator', 'Calamatic 1000', 'Calgon Carbon / SolmeteX', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMJRY454TM6RM04J99', 'Dental Vacuum Pump', NULL, 'DentalEZ', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM0TKW237ZP21MQ15S', 'Operatory Cabinetry', NULL, 'A-dec', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMBKCPYZTANKM4E1TH', 'Dental Stool (Operator)', NULL, 'Herman Miller / A-dec', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMZWG6AAAFK1P1JBEK', 'Patient Monitor (vitals)', NULL, 'Philips', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMDYA1RQT2S34Z5JGC', 'Radiography Developer / Processor (digital reader)', 'ScanX Duo', 'Air Techniques', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMCS20CNGY8BRRDY4R', 'Digital Panoramic Sensor', 'Gendex Orthoralix', 'Gendex', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMDE9QB8QV678JK8VG', 'Bonding Light (LED)', 'Woodpecker LED.B', 'Woodpecker', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM49TWYKVKW6NG9XA5', 'Dental Refrigerator (for materials)', NULL, NULL, NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMK5QA5Y39E0YFP1N2', 'X-ray Protective Lead Apron', NULL, NULL, NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMX3BFB43BD517VB44', 'Dental Cabinet Autoclave Holder', NULL, NULL, NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMS87HGGTPKF8ZHZY0', 'Sterilization Pouches & Sealer', 'Impulse Sealer', 'Prestige Medical', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM15P5VBZCZVZC6EDH', 'Dental Handpiece Maintenance Unit', 'NSK Pana-Max Maintenance', 'NSK', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM90JYQVM2NXV1W686', 'Dental Sedation Equipment (Nitrous Oxide)', 'Porter NC900', 'Porter', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMSXD11WSJ0JWYMBT4', 'Portable X-ray Unit', 'Nomad Pro 2', 'Kavo/Aribex', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM8BY4NAT7YSDR2D55', 'Infection Control Supplies (disinfectant sprayer)', NULL, NULL, NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMKEAEXQZ70W5GDPQB', 'Dental CAD/CAM Milling Unit', 'CEREC MC XL', 'Dentsply Sirona', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMD7V73NT6QRGKMTMV', 'Paperless Charting / Practice Management Computer', NULL, 'Dentrix / Eaglesoft', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM01JC0W2Q46CZYMP2', 'Autoclave Bowie-Dick Test Kit (monitoring)', NULL, NULL, NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMZ2P81V8CFD5AJTYS', 'Headlamp / Loupes', 'Orascoptic LED loupe light', 'Orascoptic', NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAM31C65GXQTCDSSVX2', 'Dental X-ray Lead Wall Barrier', NULL, NULL, NULL);
INSERT INTO equipment (equipment_id, name, model, manufacturer, notes) VALUES ('01K7J8QWAMCPBBXY1EAKFHDCAS', 'Otoscope / Exam Light', NULL, NULL, NULL);
COMMIT;
